config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  resources :ordens_de_servico
  resources :fases
  resources :sistemas
  resources :tipos
  resources :areas
  resources :coordenadorias
  resources :tacs
  resources :tcs
  resources :pas

  root to: "ordens_de_servico#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/sistema.rb
class Sistema < ApplicationRecord
end

app/controllers/sistemas_controller.rb
class SistemasController < ApplicationController
  before_action :set_sistema, only: [:show, :edit, :update, :destroy]

  # GET /sistemas
  # GET /sistemas.json
  def index
    @sistemas = Sistema.all
  end

  # GET /sistemas/1
  # GET /sistemas/1.json
  def show
  end

  # GET /sistemas/new
  def new
    @sistema = Sistema.new
  end

  # GET /sistemas/1/edit
  def edit
  end

  # POST /sistemas
  # POST /sistemas.json
  def create
    @sistema = Sistema.new(sistema_params)

    respond_to do |format|
      if @sistema.save
        format.html { redirect_to @sistema, notice: 'Sistema was successfully created.' }
        format.json { render :show, status: :created, location: @sistema }
      else
        format.html { render :new }
        format.json { render json: @sistema.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sistemas/1
  # PATCH/PUT /sistemas/1.json
  def update
    respond_to do |format|
      if @sistema.update(sistema_params)
        format.html { redirect_to @sistema, notice: 'Sistema was successfully updated.' }
        format.json { render :show, status: :ok, location: @sistema }
      else
        format.html { render :edit }
        format.json { render json: @sistema.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sistemas/1
  # DELETE /sistemas/1.json
  def destroy
    @sistema.destroy
    respond_to do |format|
      format.html { redirect_to sistemas_url, notice: 'Sistema was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sistema
      @sistema = Sistema.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def sistema_params
      params.require(:sistema).permit(:nome)
    end
end

app/helpers/sistemas_helper.rb
module SistemasHelper
end

app/views/sistemas/_form.html.erb
<%= form_with(model: sistema, local: true) do |form| %>
  <% if sistema.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(sistema.errors.count, "error") %> prohibited this sistema from being saved:</h2>

      <ul>
        <% sistema.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/sistemas/edit.html.erb
<h1>Editing Sistema</h1>

<%= render 'form', sistema: @sistema %>

<%= link_to 'Show', @sistema %> |
<%= link_to 'Back', sistemas_path %>

app/views/sistemas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Sistemas</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sistemas.each do |sistema| %>
      <tr>
        <td><%= sistema.nome %></td>
        <td><%= link_to 'Show', sistema %></td>
        <td><%= link_to 'Edit', edit_sistema_path(sistema) %></td>
        <td><%= link_to 'Destroy', sistema, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sistema', new_sistema_path %>

app/views/sistemas/new.html.erb
<h1>New Sistema</h1>

<%= render 'form', sistema: @sistema %>

<%= link_to 'Back', sistemas_path %>

app/views/sistemas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @sistema.nome %>
</p>

<%= link_to 'Edit', edit_sistema_path(@sistema) %> |
<%= link_to 'Back', sistemas_path %>