config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  resources :ordens_de_servico
  resources :fases
  resources :sistemas
  resources :tipos
  resources :areas
  resources :coordenadorias
  resources :tacs
  resources :tcs
  resources :pas

  root to: "ordens_de_servico#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/tac.rb
class Tac < ApplicationRecord
    default_scope { order 'tacs.created_at DESC' }
end

app/controllers/tacs_controller.rb
class TacsController < ApplicationController
  before_action :set_tac, only: [:show, :edit, :update, :destroy]

  # GET /tacs
  # GET /tacs.json
  def index
    @tacs = Tac.all
  end

  # GET /tacs/1
  # GET /tacs/1.json
  def show
  end

  # GET /tacs/new
  def new
    @tac = Tac.new
  end

  # GET /tacs/1/edit
  def edit
  end

  # POST /tacs
  # POST /tacs.json
  def create
    @tac = Tac.new(tac_params)

    respond_to do |format|
      if @tac.save
        format.html { redirect_to @tac, notice: 'Tac was successfully created.' }
        format.json { render :show, status: :created, location: @tac }
      else
        format.html { render :new }
        format.json { render json: @tac.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tacs/1
  # PATCH/PUT /tacs/1.json
  def update
    respond_to do |format|
      if @tac.update(tac_params)
        format.html { redirect_to @tac, notice: 'Tac was successfully updated.' }
        format.json { render :show, status: :ok, location: @tac }
      else
        format.html { render :edit }
        format.json { render json: @tac.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tacs/1
  # DELETE /tacs/1.json
  def destroy
    @tac.destroy
    respond_to do |format|
      format.html { redirect_to tacs_url, notice: 'Tac was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tac
      @tac = Tac.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tac_params
      params.require(:tac).permit(:numero)
    end
end

app/helpers/tacs_helper.rb
module TacsHelper
end

app/views/tacs/_form.html.erb
<%= form_with(model: tac, local: true) do |form| %>
  <% if tac.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tac.errors.count, "error") %> prohibited this tac from being saved:</h2>

      <ul>
        <% tac.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :numero %>
    <%= form.text_field :numero %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tacs/edit.html.erb
<h1>Editing Tac</h1>

<%= render 'form', tac: @tac %>

<%= link_to 'Show', @tac %> |
<%= link_to 'Back', tacs_path %>

app/views/tacs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tacs</h1>

<table>
  <thead>
    <tr>
      <th>Numero</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tacs.each do |tac| %>
      <tr>
        <td><%= tac.numero %></td>
        <td><%= link_to 'Show', tac %></td>
        <td><%= link_to 'Edit', edit_tac_path(tac) %></td>
        <td><%= link_to 'Destroy', tac, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tac', new_tac_path %>

app/views/tacs/new.html.erb
<h1>New Tac</h1>

<%= render 'form', tac: @tac %>

<%= link_to 'Back', tacs_path %>

app/views/tacs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Numero:</strong>
  <%= @tac.numero %>
</p>

<%= link_to 'Edit', edit_tac_path(@tac) %> |
<%= link_to 'Back', tacs_path %>