config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  resources :ordens_de_servico
  resources :fases
  resources :sistemas
  resources :tipos
  resources :areas
  resources :coordenadorias
  resources :tacs
  resources :tcs
  resources :pas

  root to: "ordens_de_servico#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/coordenadoria.rb
class Coordenadoria < ApplicationRecord
    default_scope { order 'coordenadorias.descricao ASC' }
end

app/controllers/coordenadorias_controller.rb
class CoordenadoriasController < ApplicationController
  before_action :set_coordenadoria, only: [:show, :edit, :update, :destroy]

  # GET /coordenadorias
  # GET /coordenadorias.json
  def index
    @coordenadorias = Coordenadoria.all
  end

  # GET /coordenadorias/1
  # GET /coordenadorias/1.json
  def show
  end

  # GET /coordenadorias/new
  def new
    @coordenadoria = Coordenadoria.new
  end

  # GET /coordenadorias/1/edit
  def edit
  end

  # POST /coordenadorias
  # POST /coordenadorias.json
  def create
    @coordenadoria = Coordenadoria.new(coordenadoria_params)

    respond_to do |format|
      if @coordenadoria.save
        format.html { redirect_to @coordenadoria, notice: 'Coordenadoria was successfully created.' }
        format.json { render :show, status: :created, location: @coordenadoria }
      else
        format.html { render :new }
        format.json { render json: @coordenadoria.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /coordenadorias/1
  # PATCH/PUT /coordenadorias/1.json
  def update
    respond_to do |format|
      if @coordenadoria.update(coordenadoria_params)
        format.html { redirect_to @coordenadoria, notice: 'Coordenadoria was successfully updated.' }
        format.json { render :show, status: :ok, location: @coordenadoria }
      else
        format.html { render :edit }
        format.json { render json: @coordenadoria.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /coordenadorias/1
  # DELETE /coordenadorias/1.json
  def destroy
    @coordenadoria.destroy
    respond_to do |format|
      format.html { redirect_to coordenadorias_url, notice: 'Coordenadoria was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_coordenadoria
      @coordenadoria = Coordenadoria.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def coordenadoria_params
      params.require(:coordenadoria).permit(:descricao)
    end
end

app/helpers/coordenadorias_helper.rb
module CoordenadoriasHelper
end

app/views/coordenadorias/_form.html.erb
<%= form_with(model: coordenadoria, local: true) do |form| %>
  <% if coordenadoria.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(coordenadoria.errors.count, "error") %> prohibited this coordenadoria from being saved:</h2>

      <ul>
        <% coordenadoria.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :descricao %>
    <%= form.text_field :descricao %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/coordenadorias/edit.html.erb
<h1>Editing Coordenadoria</h1>

<%= render 'form', coordenadoria: @coordenadoria %>

<%= link_to 'Show', @coordenadoria %> |
<%= link_to 'Back', coordenadorias_path %>

app/views/coordenadorias/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Coordenadorias</h1>

<table>
  <thead>
    <tr>
      <th>Descricao</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @coordenadorias.each do |coordenadoria| %>
      <tr>
        <td><%= coordenadoria.descricao %></td>
        <td><%= link_to 'Show', coordenadoria %></td>
        <td><%= link_to 'Edit', edit_coordenadoria_path(coordenadoria) %></td>
        <td><%= link_to 'Destroy', coordenadoria, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Coordenadoria', new_coordenadoria_path %>

app/views/coordenadorias/new.html.erb
<h1>New Coordenadoria</h1>

<%= render 'form', coordenadoria: @coordenadoria %>

<%= link_to 'Back', coordenadorias_path %>

app/views/coordenadorias/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Descricao:</strong>
  <%= @coordenadoria.descricao %>
</p>

<%= link_to 'Edit', edit_coordenadoria_path(@coordenadoria) %> |
<%= link_to 'Back', coordenadorias_path %>